# Generated by Django 6.0 on 2026-02-21 06:32

from django.db import migrations, models


def make_emails_unique(apps, schema_editor):
    """Ensure all emails are unique before adding UNIQUE constraint (fix empty/duplicate emails)."""
    User = apps.get_model('accounts', 'User')
    seen = set()
    for user in User.objects.all():
        email = (user.email or '').strip().lower()
        if not email or email in seen:
            user.email = f"user{user.id}@local.healthcare"
            user.save(update_fields=['email'])
        else:
            seen.add(email)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.RunPython(make_emails_unique, noop_reverse),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
