# Generated by Django 6.0 on 2026-02-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('HOSPITAL', 'Hospital'), ('HOSPITAL_ADMIN', 'Hospital Admin')], default='PATIENT', max_length=20),
        ),
    ]
