# Generated by Django 6.0 on 2026-02-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_doctorhospitalrequest_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='facilities',
            field=models.TextField(blank=True, help_text='Departments - comma separated'),
        ),
    ]
