# Generated by Django 6.0 on 2026-02-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctorprofileupdaterequest_doctorleave'),
        ('hospitals', '0005_alter_hospital_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorhospitalrequest',
            name='expected_monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected salary when sending request', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='DoctorHospitalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_assignments', to='doctors.doctorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='hospitals.hospital')),
            ],
            options={
                'verbose_name': 'Doctor Hospital Assignment',
                'verbose_name_plural': 'Doctor Hospital Assignments',
                'db_table': 'doctor_hospital_assignments',
                'unique_together': {('doctor', 'hospital')},
            },
        ),
    ]
