# Generated by Django 6.0 on 2026-02-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='verification_document',
            field=models.FileField(blank=True, help_text='Upload license or certification document for verification', null=True, upload_to='doctor_verifications/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('CARDIOLOGY', 'Cardiology'), ('DERMATOLOGY', 'Dermatology'), ('NEUROLOGY', 'Neurology'), ('ORTHOPEDICS', 'Orthopedics'), ('PEDIATRICS', 'Pediatrics'), ('PSYCHIATRY', 'Psychiatry'), ('SURGERY', 'Surgery'), ('GENERAL', 'General Medicine'), ('ONCOLOGY', 'Oncology'), ('GYNECOLOGY', 'Gynecology')], default='GENERAL', max_length=50),
        ),
    ]
