# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile_verification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='available_from',
            field=models.TimeField(default='09:00:00', help_text='Start of working hours'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_to',
            field=models.TimeField(default='17:00:00', help_text='End of working hours'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
