# Generated by Django 6.0 on 2026-02-22 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_available_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_from',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Start of working hours'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_to',
            field=models.TimeField(default=datetime.time(17, 0), help_text='End of working hours'),
        ),
    ]
