# Generated by Django 6.0 on 2026-02-22 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctorprofile_available_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('specialization', 'Specialization'), ('qualification', 'Qualification'), ('license_number', 'License Number'), ('verification_document', 'Verification Document')], max_length=50)),
                ('new_value_text', models.CharField(blank=True, max_length=500)),
                ('new_value_file', models.FileField(blank=True, null=True, upload_to='doctor_update_requests/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_update_requests', to='doctors.doctorprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_doctor_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Profile Update Request',
                'verbose_name_plural': 'Doctor Profile Update Requests',
                'db_table': 'doctor_profile_update_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_dates', to='doctors.doctorprofile')),
            ],
            options={
                'verbose_name': 'Doctor Leave',
                'verbose_name_plural': 'Doctor Leave',
                'db_table': 'doctor_leave',
                'ordering': ['leave_date'],
                'unique_together': {('doctor', 'leave_date')},
            },
        ),
    ]
